# 这个notebook试图实现产生奇数阶幻方的代码

In [1]:
import numpy as np

In [27]:
def fun(n):
    """
    Try to generate a 幻方 of n orders
    """
    if n % 2 == 0 :
        print("n has to be an odd number. Please check the n value")
        return None
    
    holder = np.zeros((n,n), dtype=np.int64)
    tot = n ** 2
    
    # The location of the current
    coor = [0, (n-1)//2]
    val = 1
    
    while True:
        
        # Update the holder
        holder[coor[0], coor[1]] = val
        
        # If we have finished all update, then return
        if val >= tot:
            return holder
        
        # Update the indicator of the step number
        val += 1
        
        # Find the next location to fill the number
        
        # initial guess
        tmp = [(coor[0] - 1) % n, (coor[1] + 1) % n]
        
        if holder[tmp[0], tmp[1]] != 0:
            coor = [(coor[0] + 1) % n, coor[1] % n]
        else:
            coor[:] = tmp[:]
            

In [32]:
res = fun(n=5)
print(res)
print(np.sum(res, axis=0))
print(np.sum(res, axis=1))
print(np.trace(res))
print(np.trace(res[::-1]))

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]
[65 65 65 65 65]
[65 65 65 65 65]
65
65


In [33]:
res = fun(n=7)
print(res)
print(np.sum(res, axis=0))
print(np.sum(res, axis=1))
print(np.trace(res))
print(np.trace(res[::-1]))

[[30 39 48  1 10 19 28]
 [38 47  7  9 18 27 29]
 [46  6  8 17 26 35 37]
 [ 5 14 16 25 34 36 45]
 [13 15 24 33 42 44  4]
 [21 23 32 41 43  3 12]
 [22 31 40 49  2 11 20]]
[175 175 175 175 175 175 175]
[175 175 175 175 175 175 175]
175
175


In [34]:
res = fun(n=9)
print(res)
print(np.sum(res, axis=0))
print(np.sum(res, axis=1))
print(np.trace(res))
print(np.trace(res[::-1]))

[[47 58 69 80  1 12 23 34 45]
 [57 68 79  9 11 22 33 44 46]
 [67 78  8 10 21 32 43 54 56]
 [77  7 18 20 31 42 53 55 66]
 [ 6 17 19 30 41 52 63 65 76]
 [16 27 29 40 51 62 64 75  5]
 [26 28 39 50 61 72 74  4 15]
 [36 38 49 60 71 73  3 14 25]
 [37 48 59 70 81  2 13 24 35]]
[369 369 369 369 369 369 369 369 369]
[369 369 369 369 369 369 369 369 369]
369
369
